build:
  environment:
    node: v14.0.0
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [js-scrutinizer-run]
    coverage:
      tests:
        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover
